import React from 'react';
import { Button, Box, Tooltip } from '@chakra-ui/react';

const InfoButtons: React.FC = () => {
    const disclaimer = "This content was generated by an AI language model. It may not be entirely accurate or up-to-date.";
    const info = "";
    return (
 
        <Box display="flex" justifyContent="center" alignItems="center" gap={4}>
          <Tooltip label={disclaimer} aria-label="Disclaimer Tooltip">
            <Button size='lg' bg='white'>
              Disclaimer
            </Button>
          </Tooltip>
          <Tooltip label="This is the info information" aria-label="Info Tooltip">
            <Button size='lg' bg='white'>
              Info
            </Button>
          </Tooltip>
        </Box>
      );
};

export default InfoButtons;