import React from 'react';
import { Button, Box, Tooltip } from '@chakra-ui/react';

const InfoButtons: React.FC = () => {
    const disclaimer = "This content was generated by an AI language model. It may not be entirely accurate or up-to-date.";
    const info = `The Product Manager Accelerator Program is designed to support PM professionals through every stage of their career. From students looking for entry-level jobs to Directors looking to take on a leadership role, our program has helped over hundreds of students fulfill their career aspirations.\n\nOur Product Manager Accelerator community are ambitious and committed. Through our program they have learnt, honed and developed new PM and leadership skills, giving them a strong foundation for their future endeavours.\n\nLearn product management for free today on our YouTube channel:\nhttps://www.youtube.com/c/drnancyli?sub_confirmation=1\n\nApp created by: Ryan Bui`;

    return (
 
        <Box display="flex" justifyContent="center" alignItems="center" gap={4}>
          <Tooltip label={disclaimer} aria-label="Disclaimer Tooltip">
            <Button size='lg' bg='white'>
              Disclaimer
            </Button>
          </Tooltip>
          <Tooltip label={info} aria-label="Info Tooltip" whiteSpace = "pre-line">
            <Button size='lg' bg='white'>
              Info
            </Button>
          </Tooltip>
        </Box>
      );
};

export default InfoButtons;